<?php
// Include database config file => to get our PDO object 
require_once 'includes/db_connect.php';
$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);

// Below is just a copy of DELETE Statement Template Generated by MySQL (phpMyAdmin):
/*
UPDATE `posts` 
SET 
    `post_id`='[value-1]',
    `title`='[value-2]',
    `body`='[value-3]',
    `author`='[value-4]',
    `published`='[value-5]',
    `released`='[value-6]' 
WHERE 1
*/

// Updating a record:
// Assuming that we will update the record (post) with id value of "4"
$postId = 2; // This is the post id for the record that we need to update

// Remember the post tile is "Adobe Dreamweaver"
// We will change it with the new value of this postTitle variable:
$pTitle = "PHP and MySQL";

// Prepare:
$stmt = $pdo->prepare('UPDATE posts SET title =:postTitle WHERE post_id=:postId');

// Execute:
/*
PHP.NET: execute() => Returns "true" on success or "false" on failure.
In other words, execute() returns true if the SQL Statement run successfully
But that's doesn't mean that (change)* has been applied to my table
*change => insert/update/delete

PHP.NET: rowCount() => returns the number of rows affected 
by the last DELETE, INSERT, or UPDATE statement 
executed by the corresponding PDOStatement object.

Link: https://www.php.net/manual/en/pdostatement.rowcount
*/

/*
NOTE: 
The following code is NOT useful => $isUpdated will be always "true"
if the SQL Statement are run successfully even if no record has been updated!

You can try it by passing id that doesn't exist, the varaible isUpdated will be "true"!
*/
// $isUpdated = $stmt->execute(['postTitle'=>$pTitle, 'postId'=>$postId]); 
// for testing:
/*
echo "<hr>isDeleted: ";
var_dump($isDeleted); // bool(true)
echo "<hr>";
*/

$stmt->execute(['postTitle'=>$pTitle, 'postId'=>$postId]);

$count = $stmt->rowCount();
echo "<hr>Row Update Count: ";
var_dump($count); // will return 1 if any row has been updated, return 0 if nothing changed OR record not found
/*
Output: Row Update Count: int(0)
*/
echo "<hr>";

echo (($count==1) ? "<br>Post has been updated!" : "<br>Sorry updating post is not done!");


// we will skip the HTML template => we can skip the closing php tag